import type { Project, Post } from "./types";

/** slugify a project/post name */
export function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

/*
 * `sheet` marks a project imported from a presentation board: alongside the
 * cropped card render in /projects/<img>.jpg there is a full project sheet in
 * /projects/sheets/<img>.jpg carrying the views, drawings and specs. Both go
 * into image_urls so the lightbox gallery can page between them.
 */
type Seed = Omit<Project, "slug" | "image_url"> & { img: string; sheet?: boolean };

const raw: Seed[] = [
  // ---------- Mechanical & Industrial Engineering ----------
  { name: "Centrifugal Pump", category: "mechanical", img: "pump", featured: true, sort: 1,
    blurb: "Pumps from 1.5 kW up to 132 kW — each fully engineered and now in production in the Middle East.",
    tags: ["CAD", "Drawings", "Industrial"] },
  { name: "Butterfly Valve", category: "mechanical", img: "valve", sort: 2,
    blurb: "Over 150 DWG drawings rebuilt as fully parametric 3D models with tolerances for PELICAN WORLDWIDE (NL).",
    tags: ["Autodesk Inventor", "Parametric"] },
  { name: "Crane Pipe Connections", category: "mechanical", img: "crane", sort: 3,
    blurb: "3D + 2D assemblies of LUG, PIPE, BUMP and BAYONET joints in 90° and 360° positions.",
    tags: ["Assembly", "Piping"] },
  { name: "Foam Dispenser", category: "mechanical", img: "foam", featured: true, sort: 4,
    blurb: "Complex multi-part assembly — adapter, seal, housing, washer and nut around a bent internal air-hose.",
    tags: ["Assembly", "Simulation"] },
  { name: "Two-Component Glue Mixer", category: "mechanical", img: "mixer", sort: 5,
    blurb: "Helical static mixer inside a housing, geometry tuned so two components blend fully in a single pass.",
    tags: ["CAD", "Flow"] },
  { name: "Pump Housing — Clamp", category: "mechanical", img: "clamp", sort: 6,
    blurb: "Print-ready pump-housing clamp delivered with fully dimensioned technical drawings.",
    tags: ["Print-ready", "Drawings"] },
  { name: "Ice Fishing Stand", category: "mechanical", img: "icefishing", sort: 7,
    blurb: "Complete 3D assembly of an ice-fishing stand with 2D general-dimension drawings.",
    tags: ["Assembly", "Product"] },
  { name: "Pergola Extrusion Kit", category: "mechanical", img: "pergola", sort: 8,
    blurb: "Pergola profiles with an internal aluminium reinforcement — four section variants.",
    tags: ["Extrusion", "Architecture"] },
  { name: "CNC Production Part", category: "mechanical", img: "cncpart", sort: 9,
    blurb: "Curved CNC part modelled from a 2D drawing and prepared for machining.",
    tags: ["CNC", "DFM"] },
  { name: "6061 Aluminium Bracket", category: "mechanical", img: "alu6061", sort: 10,
    blurb: "Motorsport bracket engineered for CNC machining from 6061 aluminium.",
    tags: ["CNC", "Automotive"] },
  { name: "DIY CNC Router Parts", category: "mechanical", img: "cncrouter", sort: 11,
    blurb: "Machined on a self-built, 3D-printed CNC router in 18 mm beech.",
    tags: ["CNC", "Woodwork"] },
  { name: "Massage Roller", category: "mechanical", img: "massager", sort: 12,
    blurb: "Foam-roller assembly with movable pins; hole and rod tolerances tuned for smooth motion.",
    tags: ["Assembly", "Consumer"] },
  { name: "T-Part", category: "mechanical", img: "tpart", sort: 13,
    blurb: "Print-ready component supplied with complete section-view documentation.",
    tags: ["Print-ready", "Docs"] },

  // ---------- Product Design & 3D Modeling ----------
  { name: "The Back Dragon", category: "product", img: "backdragon", featured: true, sort: 14,
    blurb: "Flagship back-massage product — one end heats a ceramic ball to 100 °C, the other cools, all without melting the plastic. Shown at lectures in the USA.",
    tags: ["Product Design", "Prototype"] },
  { name: "Toothbrush", category: "product", img: "toothbrush", sort: 15,
    blurb: "Two-tone toothbrush prototype modelled and prepared for 3D printing.",
    tags: ["Product Design", "Consumer"] },
  { name: "Razer Naga Mouse", category: "product", img: "mouse", featured: true, sort: 16,
    blurb: "An existing gaming mouse reverse-measured part-by-part and rebuilt in SolidWorks.",
    tags: ["Reverse Eng.", "SolidWorks"] },
  { name: "Car Seat", category: "product", img: "carseat", sort: 17,
    blurb: "Automotive seat cushion modelled directly from a 3D scan file.",
    tags: ["Scan-to-CAD", "Automotive"] },
  { name: "Sophia Shelf", category: "product", img: "shelf", sort: 18,
    blurb: "Self-adjusting minimalist shelf for architecture studio Saana — buyers choose their own dimensions.",
    tags: ["Furniture", "Product Design"] },
  { name: "Trash Bin", category: "product", img: "trashbin", sort: 19,
    blurb: "A workshop sketch refined into a full technical assembly and finished renders.",
    tags: ["Sheet Metal", "Product"] },
  { name: "iPhone Case", category: "product", img: "iphonecase", sort: 20,
    blurb: "Perforated protective case modelled with full dimensioning.",
    tags: ["Product Design", "Consumer"] },
  { name: "Wheel Rim", category: "product", img: "rim", featured: true, sort: 21,
    blurb: "Modern wheel-model prototypes for a rim manufacturer, prototyped and 3D printed.",
    tags: ["Automotive", "Prototype"] },
  { name: "Plastic Bouquet", category: "product", img: "bouquet", sort: 22,
    blurb: "Decorative tulip-bouquet vase modelled and rendered for production.",
    tags: ["Product Design", "Consumer"] },
  { name: "Fishing Bait", category: "product", img: "fishingbait", sort: 23,
    blurb: "Designed and prototyped for a Danish company — now their best-selling bait.",
    tags: ["Product Design", "Prototype"] },
  { name: "Children's Toy Car", category: "product", img: "toycar", sort: 24,
    blurb: "Pull-back toy car with a full internal gear-train, designed and printed.",
    tags: ["Mechanism", "Toy"] },
  { name: "Benda Pals Toy", category: "product", img: "bendapals", sort: 25,
    blurb: "Poseable creature toy with head, limbs and wings modelled separately for printing.",
    tags: ["Toy", "Print-ready"] },
  { name: "Front Man Mask", category: "product", img: "frontman", sort: 26,
    blurb: "Low-poly character mask, modelled and 3D printed.",
    tags: ["Cosplay", "Print"] },
  { name: "Alfa Romeo Grille", category: "product", img: "alfagrill", sort: 27,
    blurb: "A 40 × 35 cm front honeycomb grille for Alfa Romeo.",
    tags: ["Automotive", "Print"] },
  { name: "Rain Barrel", category: "product", img: "rainbarrel", sort: 28,
    blurb: "From a customer photo and sketch to a finished rain-barrel with a matching step stool.",
    tags: ["Concept-to-Part", "Product"] },
  { name: "Cooling Station", category: "product", img: "coolingstation", sort: 29,
    blurb: "200 mm-fan cooling station split into two printable pieces to cut cost and support.",
    tags: ["Product Design", "DFM"] },

  // ---------- 3D Printing & Reverse Engineering ----------
  { name: "PET-G Replacement Parts", category: "printing", img: "petg", sort: 30,
    blurb: "Reverse-engineered replacement parts you can't buy anywhere, printed in PET-G.",
    tags: ["Reverse Eng.", "PET-G"] },
  { name: "Taipei 101", category: "printing", img: "taipei", featured: true, sort: 31,
    blurb: "Architectural scale model, modelled and 3D printed as a single piece.",
    tags: ["Scale Model", "Print"] },
  { name: "Reverse-Engineered Impeller", category: "printing", img: "impeller", featured: true, sort: 32,
    blurb: "Machine impeller rebuilt and printed with 5 walls at 100 % infill (250 g).",
    tags: ["Reverse Eng.", "Heavy-duty"] },
  { name: "PET-G Galaxy Sprocket", category: "printing", img: "petggear", sort: 33,
    blurb: "Factory machine sprocket 3D printed in PET-G for multi-purpose production.",
    tags: ["PET-G", "Spare Part"] },
  { name: "Biathlon Rifle Sight Part", category: "printing", img: "biathlon", sort: 34,
    blurb: "3D-printed sight component — 25 g vs 250 g makes a big difference over half a metre.",
    tags: ["Print", "Lightweight"] },
  { name: "Textured Bowls", category: "printing", img: "bowls", sort: 35,
    blurb: "Decorative faceted bowl printed to a salon's exact specification.",
    tags: ["Print", "Decorative"] },
  { name: "Devotional Statues", category: "printing", img: "statues", sort: 36,
    blurb: "Madonna statues printed at 20, 30 and 50 cm.",
    tags: ["Print", "Sculpture"] },
  { name: "GoPro Tank Mount", category: "printing", img: "gopro", sort: 37,
    blurb: "GoPro mount for a motorcycle tank, printed in PET-G at 100 % infill.",
    tags: ["PET-G", "Automotive"] },

  // ---------- 2026 portfolio (imported from Presentation_20260727.pdf) ----------
  { name: "Custom Clamp with FEA", category: "mechanical", img: "clamp-fea", sheet: true, featured: true, sort: 38,
    blurb: "Developed from the client's initial idea to a production-ready clamp in PA6 GF30 and TPU 60A. Finite element analysis verified von Mises stress and displacement under load before release.",
    tags: ["FEA", "Injection Molding", "STEP / STL", "2D DWG"] },
  { name: "Bush Craft & Skinner Knives", category: "product", img: "knives", sheet: true, featured: true, sort: 39,
    blurb: "Two full-tang stainless knives designed from a client sketch, prototyped and put into production — ergonomic textured handles and jimping on the spine for thumb control.",
    tags: ["Product Design", "Production", "Renders"] },
  { name: "Rotomolded Cooler Box", category: "product", img: "coolerbox", sheet: true, sort: 40,
    blurb: "High-performance cooler with thick insulated walls, dual latches, an integrated strap-loop system and a drain plug — delivered with six orthographic views and full drawings.",
    tags: ["Rotomolding", "Assembly", "Outdoor"] },
  { name: "Fishing Pliers with Rubber Grip", category: "product", img: "pliers", sheet: true, sort: 41,
    blurb: "185 mm stainless pliers with TPR overmoulded grips, serrated jaws and a built-in line cutter. Six-part assembly documented to ±0.02 in.",
    tags: ["Overmoulding", "Assembly", "Fishing"] },
  { name: "Grip — 2D to 3D and Back", category: "printing", img: "grip", sheet: true, sort: 42,
    blurb: "A supplied 2D technical drawing rebuilt as an exact TPR grip in CAD, then re-documented as a fresh 2D drawing generated from the model for production consistency.",
    tags: ["Reverse Eng.", "Drawings", "STEP / STL"] },
  { name: "Ergonomic Chair Shell", category: "product", img: "chairshell", sheet: true, featured: true, sort: 43,
    blurb: "Injection-moulded PP/HDPE seat shell, 620 × 540 × 410 mm at ~2.3 kg. A honeycomb seat structure and reinforcing ribs carry 120 kg at 2.5–3.5 mm wall thickness.",
    tags: ["Injection Molding", "Furniture", "DFM"] },
  { name: "Waterproof Tackle Box", category: "product", img: "tacklebox", sheet: true, sort: 44,
    blurb: "From client brief and sketches to a finished product — sealed case with a compartment tray, moulded latches and an embossed brand face.",
    tags: ["Product Design", "Injection Molding", "Renders"] },
  { name: "Nasal Spray Housing", category: "product", img: "nasalspray", sheet: true, sort: 45,
    blurb: "69 mm injection-moulded spray with a living hinge and clip closure, detailed down to the 0.3 mm hinge section and the clip engagement.",
    tags: ["Living Hinge", "Medical", "Injection Molding"] },
  { name: "Aroma Nasal Inhaler", category: "product", img: "aromainhaler", sheet: true, sort: 46,
    blurb: "Hand sketch to production: a two-part PP inhaler, 54.7 mm tall at 18 g, with twin nozzles and a knurled screw base — modelled, exploded and dimensioned.",
    tags: ["Concept-to-Part", "PP", "Exploded View"] },
  { name: "Nasal Aspirator", category: "product", img: "nasalaspirator", sheet: true, sort: 47,
    blurb: "157 mm manual aspirator with a soft silicone tip, transparent collection chamber and piston suction. Designed to strip down for boiling, steam or UV sterilisation.",
    tags: ["Medical", "Silicone", "Assembly"] },
  { name: "Circular Aroma Diffuser", category: "product", img: "aromadiffuser", sheet: true, sort: 48,
    blurb: "25.8 mm perforated PP diffuser at 6 g, with an integrated clip for attaching to vents and other surfaces.",
    tags: ["Product Design", "PP", "Compact"] },
  { name: "Exhaust Manifold", category: "mechanical", img: "manifold", sheet: true, featured: true, sort: 49,
    blurb: "A redesigned four-into-one manifold: smoother runner transitions, reinforced junctions and optimised wall thickness. Sand-cast aluminium with CNC-machined flange faces.",
    tags: ["Sand Casting", "CNC", "Automotive"] },
  { name: "Pump Series — 29 Models", category: "mechanical", img: "pumps29", sheet: true, sort: 50,
    blurb: "A full ANSI pump range modelled across every size and version — 29 models in STL, MTL/LTL and XLTL groups, each with matching 2D drawings.",
    tags: ["ANSI", "Series CAD", "Drawings"] },
  { name: "Modular Puzzle Bracelet", category: "product", img: "bracelet", sheet: true, sort: 51,
    blurb: "Each link carries an integrated male/female locking mechanism for tool-free assembly. The full chain was digitally validated for fit and articulation, then rendered in ten finishes.",
    tags: ["Mechanism", "Jewellery", "Renders"] },
  { name: "AMORE Ring", category: "printing", img: "amorering", sheet: true, sort: 52,
    blurb: "3D-printed ring with an engraved AMORE logo and vertical inner ribs for grip. Drawn across ten sizes from Ø18.40 to Ø25.70 mm.",
    tags: ["3D Print", "Sizing Set", "Fashion"] },
  { name: "Mechanical Pencil", category: "product", img: "pencil", sheet: true, sort: 53,
    blurb: "141 mm drafting pencil at 21.5 g — hexagonal 9 mm body across flats, 0.5 mm lead, in aluminium, brass, steel and ABS.",
    tags: ["Product Design", "Precision", "Drawings"] },
  { name: "Collapsible Baby Bottle", category: "product", img: "babybottle", sheet: true, sort: 54,
    blurb: "A bottle that telescopes from 120 mm down to a compact 66 mm for storage — five-part injection-moulded assembly with an exploded build sequence.",
    tags: ["Mechanism", "Injection Molding", "Baby"] },
  { name: "Secure Bottle", category: "product", img: "securebottle", sheet: true, sort: 55,
    blurb: "Client sketches turned into a working prototype: 256 mm insulated bottle with an integrated handle and a lid built for one-handed use, sized to sit in a cup holder.",
    tags: ["Prototype", "Injection Molding", "Consumer"] },
  { name: "Wheelie Bins — 3 Sizes", category: "product", img: "trashcan3", sheet: true, sort: 56,
    blurb: "96, 64 and 35 gallon wheeled bins modelled as one family, each delivered in STEP and STL with matching views.",
    tags: ["Product Family", "Rotomolding", "STEP / STL"] },
  { name: "Foosball Player", category: "product", img: "foosball", sheet: true, sort: 57,
    blurb: "Table-football figure modelled for plastic injection moulding, with every detail resolved for mould manufacture and a smooth surface finish.",
    tags: ["Injection Molding", "Character", "ABS / PP"] },
  { name: "Robot Toy", category: "product", img: "toyrobot", sheet: true, sort: 58,
    blurb: "Children's toy in textured black ABS, designed for optimal manufacturability — tolerances, draft and functional features all defined for the mould.",
    tags: ["Toy", "Injection Molding", "Tolerances"] },
  { name: "Horse Head Chocolate Mold", category: "mechanical", img: "horsemold", sheet: true, sort: 59,
    blurb: "A 16-cavity chocolate mould, 241.4 × 222.2 mm, shaped so fine mane detail releases cleanly. Delivered with STEP, DTL tooling files and drawings.",
    tags: ["Tooling", "Food Grade", "DTL"] },
  { name: "Copper Mug", category: "product", img: "mug", sheet: true, sort: 60,
    blurb: "16 oz copper mug with a food-safe 304 stainless lining, a cinched corset waist and decorative lacing — built for metal spinning and deep drawing.",
    tags: ["Metal Spinning", "Deep Drawing", "Hospitality"] },
  { name: "NLL Trophy", category: "product", img: "trophy", sheet: true, sort: 61,
    blurb: "Trophy modelled from customer dimensions and reference photos, matching the original proportions and ready for CNC machining, printing or casting.",
    tags: ["CNC", "Casting", "Renders"] },
  { name: "Craw Lure", category: "product", img: "craw", sheet: true, featured: true, sort: 62,
    blurb: "Articulated crawfish lure built from client reference images and dimensional requirements — optimised for injection moulding and assembly.",
    tags: ["Injection Molding", "Fishing", "Assembly"] },
  { name: "Segmented Fish Bait", category: "product", img: "fishbait3", sheet: true, sort: 63,
    blurb: "A 3¼\" three-segment articulated lure with a diving lip and connection loops, engineered to the supplied drawing at roughly 6 g.",
    tags: ["Fishing", "ABS", "Renders"] },
  { name: "Renew Fishing Lure Range", category: "product", img: "lures", sheet: true, sort: 64,
    blurb: "Six lures — Dice, two Minnows, two Paddle Gills and a Swim Shad — each modelled and drawn for vacuum casting in 8400 rubber.",
    tags: ["Vacuum Casting", "Product Family", "Fishing"] },
  { name: "Plastisol Lure", category: "product", img: "plastisollure", sheet: true, sort: 65,
    blurb: "Anatomically detailed plastisol lure — scaled body, fins, tail and gill plate — with cavity features built in for a two-part mould.",
    tags: ["Two-Part Mold", "Fishing", "STEP / STL"] },
  { name: "Pufferfish Toy", category: "product", img: "pufferfish", sheet: true, sort: 66,
    blurb: "66 mm child-safe toy in ABS/TPE, covered in textured bumps for tactile stimulation and optimised for plastic injection moulding.",
    tags: ["Toy", "ABS / TPE", "Child-safe"] },
  { name: "Brujula 82 Pendant", category: "printing", img: "brujula", sheet: true, sort: 67,
    blurb: "Compass-inspired pendant and keychain with a central compass rose, two skulls and engraved text — optimised for high-quality 3D printing.",
    tags: ["3D Print", "Accessory", "Renders"] },
  { name: "Silicone Mushroom Grow Bag", category: "product", img: "mushroombag", sheet: true, sort: 68,
    blurb: "Concept sketch to 3D prototype: a reusable 508 × 254 × 127 mm food-grade silicone cultivation bag with reinforced edges and a Ø61 mm gas-exchange opening.",
    tags: ["Silicone", "Concept-to-Part", "Food Grade"] },
  { name: "3D Scan to Parametric Model", category: "printing", img: "scan2cad", sheet: true, featured: true, sort: 69,
    blurb: "A high-resolution scan rebuilt as a fully parametric CAD model — every functional surface and critical feature preserved, and editable for future revisions.",
    tags: ["Reverse Eng.", "Parametric", "Scan-to-CAD"] },
  { name: "Reverse Engineering from Scan Data", category: "printing", img: "revengscan", sheet: true, sort: 70,
    blurb: "Scanned parts turned into precise CAD models ready for manufacturing, optimised for FDM/SLA printing or plastic injection moulding.",
    tags: ["Reverse Eng.", "FDM / SLA", "STEP / STL / EPRT"] },
  { name: "Reverse-Engineered Plastic Enclosure", category: "printing", img: "revengenclosure", sheet: true, sort: 71,
    blurb: "A damaged enclosure scanned and fully reconstructed — original geometry and every functional feature restored, ready for injection moulding.",
    tags: ["Reverse Eng.", "Repair", "Injection Molding"] },
  { name: "WM 770 Brake Component", category: "mechanical", img: "wm770", sheet: true, sort: 72,
    blurb: "Metal actuated brake-system component designed for reliable operation and easy integration, delivered as coated metal parts with full drawings.",
    tags: ["Metal Parts", "Industrial", "Drawings"] },
  { name: "Chocolate Bow & Mold", category: "mechanical", img: "chocolatebow", sheet: true, sort: 73,
    blurb: "A 3 × 3 cm chocolate bow with a matching two-part mould — smooth surfaces for a clean finish, minimal undercut and easy top-open demoulding.",
    tags: ["Tooling", "Two-Part Mold", "Confectionery"] },
  { name: "Square & Circular Aluminium Molds", category: "mechanical", img: "aluminummolds", sheet: true, sort: 74,
    blurb: "CNC-machined aluminium moulds in circular and square cavity layouts with an engraved bird motif, delivered production-ready with realistic renders.",
    tags: ["CNC", "Tooling", "Aluminium"] },
  { name: "Gear Calculator", category: "mechanical", img: "gearcalculator", sheet: true, sort: 75,
    blurb: "A wooden gear-calculator assembly measured by hand and reconstructed in CAD — original geometry and operating mechanism preserved for digital manufacturing.",
    tags: ["Reverse Eng.", "Mechanism", "CNC / Laser"] },
  { name: "Golf Box Prototype", category: "printing", img: "golfbox", sheet: true, sort: 76,
    blurb: "Built from sketches and reference images into a complete model for prototype validation, including a rotate mechanism and fold-out stand.",
    tags: ["Prototype", "FDM / SLA", "Mechanism"] },
  { name: "Industrial Furnace RT-1121M", category: "mechanical", img: "furnace", sheet: true, sort: 77,
    blurb: "A 6.59 m three-section steel furnace rebuilt in 3D from an old drawing, then re-documented with a new fully dimensioned 2D drawing set.",
    tags: ["Industrial", "Steel", "Drawings"] },
  { name: "Gold Recovery Machine Part", category: "mechanical", img: "goldpart", sheet: true, sort: 78,
    blurb: "Injection-moulded nozzle component built for chemical and corrosion resistance, with a threaded interface sized for a precise fit in the assembly.",
    tags: ["Injection Molding", "Chemical Resistant", "Industrial"] },
  { name: "Decorative Swing", category: "printing", img: "swing", sheet: true, sort: 79,
    blurb: "A supplied STL rebuilt as a fully editable parametric CAD model of the swing, ready for further modification, visualisation and manufacturing.",
    tags: ["Reverse Eng.", "Parametric", "Decorative"] },
];

export const SEED_PROJECTS: Project[] = raw.map((p) => {
  const { img, sheet, ...rest } = p;
  const image_url = `/projects/${img}.jpg`;
  const image_urls = sheet ? [image_url, `/projects/sheets/${img}.jpg`] : [image_url];
  return { ...rest, slug: slugify(p.name), image_url, image_urls };
});

export const SEED_POSTS: Post[] = [
  {
    slug: "welcome-to-the-protoform-journal",
    title: "Welcome to the PROTOFORM journal",
    excerpt:
      "Notes from the workshop — how we take a sketch, a scan or an old 2D drawing and turn it into a real, manufacturable part.",
    cover_url: "/projects/bom.jpg",
    tags: ["Studio", "Process"],
    published: true,
    created_at: "2026-07-01T09:00:00Z",
    body:
      "## From idea to physical part\n\nEvery project starts the same way: a conversation about what the part has to **do**. From there we build precise, editable CAD geometry, prove it with the right calculations, and put a real prototype in your hands.\n\n- Detailed 3D design + engineering\n- Design for manufacturing\n- Complete bill of materials\n- Calculations & simulations\n- Print-ready models with drawings\n\nThis journal is where we'll share build notes, material choices and the odd war story from the bench.",
  },
  {
    slug: "why-pet-g-for-replacement-parts",
    title: "Why we reach for PET-G on replacement parts",
    excerpt:
      "When a part can't be bought anymore, PET-G is often the sweet spot between strength, temperature tolerance and printability.",
    cover_url: "/projects/petg.jpg",
    tags: ["Materials", "3D Printing"],
    published: true,
    created_at: "2026-07-10T09:00:00Z",
    body:
      "## The replacement-part problem\n\nDiscontinued parts are everywhere — a bracket, a clip, a sprocket that no supplier stocks any more. Reverse-engineering them and printing in **PET-G** gives a tough, slightly flexible part that survives real use.\n\nWe've printed everything from factory sprockets to GoPro tank mounts at 100% infill this way.",
  },
];
