-- PROTOFORM 2026 portfolio — projects imported from Presentation_20260727.pdf
-- Safe to re-run: skips rows that already exist (by slug).
-- Each row carries two images: the cropped card render and the full project
-- sheet (renders, views, dimensioned drawings, specs) as the second gallery
-- image. Edit either one in /admin, or paste any https URL.
-- Regenerate: node scripts/generate-seed-migration.mjs

INSERT INTO public.projects (slug, name, category, image_url, image_urls, blurb, tags, featured, published, sort)
VALUES
  ('custom-clamp-with-fea', 'Custom Clamp with FEA', 'mechanical', '/projects/clamp-fea.jpg', ARRAY['/projects/clamp-fea.jpg', '/projects/sheets/clamp-fea.jpg'], 'Developed from the client''s initial idea to a production-ready clamp in PA6 GF30 and TPU 60A. Finite element analysis verified von Mises stress and displacement under load before release.', ARRAY['FEA', 'Injection Molding', 'STEP / STL', '2D DWG'], true, true, 38),
  ('bush-craft-and-skinner-knives', 'Bush Craft & Skinner Knives', 'product', '/projects/knives.jpg', ARRAY['/projects/knives.jpg', '/projects/sheets/knives.jpg'], 'Two full-tang stainless knives designed from a client sketch, prototyped and put into production — ergonomic textured handles and jimping on the spine for thumb control.', ARRAY['Product Design', 'Production', 'Renders'], true, true, 39),
  ('rotomolded-cooler-box', 'Rotomolded Cooler Box', 'product', '/projects/coolerbox.jpg', ARRAY['/projects/coolerbox.jpg', '/projects/sheets/coolerbox.jpg'], 'High-performance cooler with thick insulated walls, dual latches, an integrated strap-loop system and a drain plug — delivered with six orthographic views and full drawings.', ARRAY['Rotomolding', 'Assembly', 'Outdoor'], false, true, 40),
  ('fishing-pliers-with-rubber-grip', 'Fishing Pliers with Rubber Grip', 'product', '/projects/pliers.jpg', ARRAY['/projects/pliers.jpg', '/projects/sheets/pliers.jpg'], '185 mm stainless pliers with TPR overmoulded grips, serrated jaws and a built-in line cutter. Six-part assembly documented to ±0.02 in.', ARRAY['Overmoulding', 'Assembly', 'Fishing'], false, true, 41),
  ('grip-2d-to-3d-and-back', 'Grip — 2D to 3D and Back', 'printing', '/projects/grip.jpg', ARRAY['/projects/grip.jpg', '/projects/sheets/grip.jpg'], 'A supplied 2D technical drawing rebuilt as an exact TPR grip in CAD, then re-documented as a fresh 2D drawing generated from the model for production consistency.', ARRAY['Reverse Eng.', 'Drawings', 'STEP / STL'], false, true, 42),
  ('ergonomic-chair-shell', 'Ergonomic Chair Shell', 'product', '/projects/chairshell.jpg', ARRAY['/projects/chairshell.jpg', '/projects/sheets/chairshell.jpg'], 'Injection-moulded PP/HDPE seat shell, 620 × 540 × 410 mm at ~2.3 kg. A honeycomb seat structure and reinforcing ribs carry 120 kg at 2.5–3.5 mm wall thickness.', ARRAY['Injection Molding', 'Furniture', 'DFM'], true, true, 43),
  ('waterproof-tackle-box', 'Waterproof Tackle Box', 'product', '/projects/tacklebox.jpg', ARRAY['/projects/tacklebox.jpg', '/projects/sheets/tacklebox.jpg'], 'From client brief and sketches to a finished product — sealed case with a compartment tray, moulded latches and an embossed brand face.', ARRAY['Product Design', 'Injection Molding', 'Renders'], false, true, 44),
  ('nasal-spray-housing', 'Nasal Spray Housing', 'product', '/projects/nasalspray.jpg', ARRAY['/projects/nasalspray.jpg', '/projects/sheets/nasalspray.jpg'], '69 mm injection-moulded spray with a living hinge and clip closure, detailed down to the 0.3 mm hinge section and the clip engagement.', ARRAY['Living Hinge', 'Medical', 'Injection Molding'], false, true, 45),
  ('aroma-nasal-inhaler', 'Aroma Nasal Inhaler', 'product', '/projects/aromainhaler.jpg', ARRAY['/projects/aromainhaler.jpg', '/projects/sheets/aromainhaler.jpg'], 'Hand sketch to production: a two-part PP inhaler, 54.7 mm tall at 18 g, with twin nozzles and a knurled screw base — modelled, exploded and dimensioned.', ARRAY['Concept-to-Part', 'PP', 'Exploded View'], false, true, 46),
  ('nasal-aspirator', 'Nasal Aspirator', 'product', '/projects/nasalaspirator.jpg', ARRAY['/projects/nasalaspirator.jpg', '/projects/sheets/nasalaspirator.jpg'], '157 mm manual aspirator with a soft silicone tip, transparent collection chamber and piston suction. Designed to strip down for boiling, steam or UV sterilisation.', ARRAY['Medical', 'Silicone', 'Assembly'], false, true, 47),
  ('circular-aroma-diffuser', 'Circular Aroma Diffuser', 'product', '/projects/aromadiffuser.jpg', ARRAY['/projects/aromadiffuser.jpg', '/projects/sheets/aromadiffuser.jpg'], '25.8 mm perforated PP diffuser at 6 g, with an integrated clip for attaching to vents and other surfaces.', ARRAY['Product Design', 'PP', 'Compact'], false, true, 48),
  ('exhaust-manifold', 'Exhaust Manifold', 'mechanical', '/projects/manifold.jpg', ARRAY['/projects/manifold.jpg', '/projects/sheets/manifold.jpg'], 'A redesigned four-into-one manifold: smoother runner transitions, reinforced junctions and optimised wall thickness. Sand-cast aluminium with CNC-machined flange faces.', ARRAY['Sand Casting', 'CNC', 'Automotive'], true, true, 49),
  ('pump-series-29-models', 'Pump Series — 29 Models', 'mechanical', '/projects/pumps29.jpg', ARRAY['/projects/pumps29.jpg', '/projects/sheets/pumps29.jpg'], 'A full ANSI pump range modelled across every size and version — 29 models in STL, MTL/LTL and XLTL groups, each with matching 2D drawings.', ARRAY['ANSI', 'Series CAD', 'Drawings'], false, true, 50),
  ('modular-puzzle-bracelet', 'Modular Puzzle Bracelet', 'product', '/projects/bracelet.jpg', ARRAY['/projects/bracelet.jpg', '/projects/sheets/bracelet.jpg'], 'Each link carries an integrated male/female locking mechanism for tool-free assembly. The full chain was digitally validated for fit and articulation, then rendered in ten finishes.', ARRAY['Mechanism', 'Jewellery', 'Renders'], false, true, 51),
  ('amore-ring', 'AMORE Ring', 'printing', '/projects/amorering.jpg', ARRAY['/projects/amorering.jpg', '/projects/sheets/amorering.jpg'], '3D-printed ring with an engraved AMORE logo and vertical inner ribs for grip. Drawn across ten sizes from Ø18.40 to Ø25.70 mm.', ARRAY['3D Print', 'Sizing Set', 'Fashion'], false, true, 52),
  ('mechanical-pencil', 'Mechanical Pencil', 'product', '/projects/pencil.jpg', ARRAY['/projects/pencil.jpg', '/projects/sheets/pencil.jpg'], '141 mm drafting pencil at 21.5 g — hexagonal 9 mm body across flats, 0.5 mm lead, in aluminium, brass, steel and ABS.', ARRAY['Product Design', 'Precision', 'Drawings'], false, true, 53),
  ('collapsible-baby-bottle', 'Collapsible Baby Bottle', 'product', '/projects/babybottle.jpg', ARRAY['/projects/babybottle.jpg', '/projects/sheets/babybottle.jpg'], 'A bottle that telescopes from 120 mm down to a compact 66 mm for storage — five-part injection-moulded assembly with an exploded build sequence.', ARRAY['Mechanism', 'Injection Molding', 'Baby'], false, true, 54),
  ('secure-bottle', 'Secure Bottle', 'product', '/projects/securebottle.jpg', ARRAY['/projects/securebottle.jpg', '/projects/sheets/securebottle.jpg'], 'Client sketches turned into a working prototype: 256 mm insulated bottle with an integrated handle and a lid built for one-handed use, sized to sit in a cup holder.', ARRAY['Prototype', 'Injection Molding', 'Consumer'], false, true, 55),
  ('wheelie-bins-3-sizes', 'Wheelie Bins — 3 Sizes', 'product', '/projects/trashcan3.jpg', ARRAY['/projects/trashcan3.jpg', '/projects/sheets/trashcan3.jpg'], '96, 64 and 35 gallon wheeled bins modelled as one family, each delivered in STEP and STL with matching views.', ARRAY['Product Family', 'Rotomolding', 'STEP / STL'], false, true, 56),
  ('foosball-player', 'Foosball Player', 'product', '/projects/foosball.jpg', ARRAY['/projects/foosball.jpg', '/projects/sheets/foosball.jpg'], 'Table-football figure modelled for plastic injection moulding, with every detail resolved for mould manufacture and a smooth surface finish.', ARRAY['Injection Molding', 'Character', 'ABS / PP'], false, true, 57),
  ('robot-toy', 'Robot Toy', 'product', '/projects/toyrobot.jpg', ARRAY['/projects/toyrobot.jpg', '/projects/sheets/toyrobot.jpg'], 'Children''s toy in textured black ABS, designed for optimal manufacturability — tolerances, draft and functional features all defined for the mould.', ARRAY['Toy', 'Injection Molding', 'Tolerances'], false, true, 58),
  ('horse-head-chocolate-mold', 'Horse Head Chocolate Mold', 'mechanical', '/projects/horsemold.jpg', ARRAY['/projects/horsemold.jpg', '/projects/sheets/horsemold.jpg'], 'A 16-cavity chocolate mould, 241.4 × 222.2 mm, shaped so fine mane detail releases cleanly. Delivered with STEP, DTL tooling files and drawings.', ARRAY['Tooling', 'Food Grade', 'DTL'], false, true, 59),
  ('copper-mug', 'Copper Mug', 'product', '/projects/mug.jpg', ARRAY['/projects/mug.jpg', '/projects/sheets/mug.jpg'], '16 oz copper mug with a food-safe 304 stainless lining, a cinched corset waist and decorative lacing — built for metal spinning and deep drawing.', ARRAY['Metal Spinning', 'Deep Drawing', 'Hospitality'], false, true, 60),
  ('nll-trophy', 'NLL Trophy', 'product', '/projects/trophy.jpg', ARRAY['/projects/trophy.jpg', '/projects/sheets/trophy.jpg'], 'Trophy modelled from customer dimensions and reference photos, matching the original proportions and ready for CNC machining, printing or casting.', ARRAY['CNC', 'Casting', 'Renders'], false, true, 61),
  ('craw-lure', 'Craw Lure', 'product', '/projects/craw.jpg', ARRAY['/projects/craw.jpg', '/projects/sheets/craw.jpg'], 'Articulated crawfish lure built from client reference images and dimensional requirements — optimised for injection moulding and assembly.', ARRAY['Injection Molding', 'Fishing', 'Assembly'], true, true, 62),
  ('segmented-fish-bait', 'Segmented Fish Bait', 'product', '/projects/fishbait3.jpg', ARRAY['/projects/fishbait3.jpg', '/projects/sheets/fishbait3.jpg'], 'A 3¼" three-segment articulated lure with a diving lip and connection loops, engineered to the supplied drawing at roughly 6 g.', ARRAY['Fishing', 'ABS', 'Renders'], false, true, 63),
  ('renew-fishing-lure-range', 'Renew Fishing Lure Range', 'product', '/projects/lures.jpg', ARRAY['/projects/lures.jpg', '/projects/sheets/lures.jpg'], 'Six lures — Dice, two Minnows, two Paddle Gills and a Swim Shad — each modelled and drawn for vacuum casting in 8400 rubber.', ARRAY['Vacuum Casting', 'Product Family', 'Fishing'], false, true, 64),
  ('plastisol-lure', 'Plastisol Lure', 'product', '/projects/plastisollure.jpg', ARRAY['/projects/plastisollure.jpg', '/projects/sheets/plastisollure.jpg'], 'Anatomically detailed plastisol lure — scaled body, fins, tail and gill plate — with cavity features built in for a two-part mould.', ARRAY['Two-Part Mold', 'Fishing', 'STEP / STL'], false, true, 65),
  ('pufferfish-toy', 'Pufferfish Toy', 'product', '/projects/pufferfish.jpg', ARRAY['/projects/pufferfish.jpg', '/projects/sheets/pufferfish.jpg'], '66 mm child-safe toy in ABS/TPE, covered in textured bumps for tactile stimulation and optimised for plastic injection moulding.', ARRAY['Toy', 'ABS / TPE', 'Child-safe'], false, true, 66),
  ('brujula-82-pendant', 'Brujula 82 Pendant', 'printing', '/projects/brujula.jpg', ARRAY['/projects/brujula.jpg', '/projects/sheets/brujula.jpg'], 'Compass-inspired pendant and keychain with a central compass rose, two skulls and engraved text — optimised for high-quality 3D printing.', ARRAY['3D Print', 'Accessory', 'Renders'], false, true, 67),
  ('silicone-mushroom-grow-bag', 'Silicone Mushroom Grow Bag', 'product', '/projects/mushroombag.jpg', ARRAY['/projects/mushroombag.jpg', '/projects/sheets/mushroombag.jpg'], 'Concept sketch to 3D prototype: a reusable 508 × 254 × 127 mm food-grade silicone cultivation bag with reinforced edges and a Ø61 mm gas-exchange opening.', ARRAY['Silicone', 'Concept-to-Part', 'Food Grade'], false, true, 68),
  ('3d-scan-to-parametric-model', '3D Scan to Parametric Model', 'printing', '/projects/scan2cad.jpg', ARRAY['/projects/scan2cad.jpg', '/projects/sheets/scan2cad.jpg'], 'A high-resolution scan rebuilt as a fully parametric CAD model — every functional surface and critical feature preserved, and editable for future revisions.', ARRAY['Reverse Eng.', 'Parametric', 'Scan-to-CAD'], true, true, 69),
  ('reverse-engineering-from-scan-data', 'Reverse Engineering from Scan Data', 'printing', '/projects/revengscan.jpg', ARRAY['/projects/revengscan.jpg', '/projects/sheets/revengscan.jpg'], 'Scanned parts turned into precise CAD models ready for manufacturing, optimised for FDM/SLA printing or plastic injection moulding.', ARRAY['Reverse Eng.', 'FDM / SLA', 'STEP / STL / EPRT'], false, true, 70),
  ('reverse-engineered-plastic-enclosure', 'Reverse-Engineered Plastic Enclosure', 'printing', '/projects/revengenclosure.jpg', ARRAY['/projects/revengenclosure.jpg', '/projects/sheets/revengenclosure.jpg'], 'A damaged enclosure scanned and fully reconstructed — original geometry and every functional feature restored, ready for injection moulding.', ARRAY['Reverse Eng.', 'Repair', 'Injection Molding'], false, true, 71),
  ('wm-770-brake-component', 'WM 770 Brake Component', 'mechanical', '/projects/wm770.jpg', ARRAY['/projects/wm770.jpg', '/projects/sheets/wm770.jpg'], 'Metal actuated brake-system component designed for reliable operation and easy integration, delivered as coated metal parts with full drawings.', ARRAY['Metal Parts', 'Industrial', 'Drawings'], false, true, 72),
  ('chocolate-bow-and-mold', 'Chocolate Bow & Mold', 'mechanical', '/projects/chocolatebow.jpg', ARRAY['/projects/chocolatebow.jpg', '/projects/sheets/chocolatebow.jpg'], 'A 3 × 3 cm chocolate bow with a matching two-part mould — smooth surfaces for a clean finish, minimal undercut and easy top-open demoulding.', ARRAY['Tooling', 'Two-Part Mold', 'Confectionery'], false, true, 73),
  ('square-and-circular-aluminium-molds', 'Square & Circular Aluminium Molds', 'mechanical', '/projects/aluminummolds.jpg', ARRAY['/projects/aluminummolds.jpg', '/projects/sheets/aluminummolds.jpg'], 'CNC-machined aluminium moulds in circular and square cavity layouts with an engraved bird motif, delivered production-ready with realistic renders.', ARRAY['CNC', 'Tooling', 'Aluminium'], false, true, 74),
  ('gear-calculator', 'Gear Calculator', 'mechanical', '/projects/gearcalculator.jpg', ARRAY['/projects/gearcalculator.jpg', '/projects/sheets/gearcalculator.jpg'], 'A wooden gear-calculator assembly measured by hand and reconstructed in CAD — original geometry and operating mechanism preserved for digital manufacturing.', ARRAY['Reverse Eng.', 'Mechanism', 'CNC / Laser'], false, true, 75),
  ('golf-box-prototype', 'Golf Box Prototype', 'printing', '/projects/golfbox.jpg', ARRAY['/projects/golfbox.jpg', '/projects/sheets/golfbox.jpg'], 'Built from sketches and reference images into a complete model for prototype validation, including a rotate mechanism and fold-out stand.', ARRAY['Prototype', 'FDM / SLA', 'Mechanism'], false, true, 76),
  ('industrial-furnace-rt-1121m', 'Industrial Furnace RT-1121M', 'mechanical', '/projects/furnace.jpg', ARRAY['/projects/furnace.jpg', '/projects/sheets/furnace.jpg'], 'A 6.59 m three-section steel furnace rebuilt in 3D from an old drawing, then re-documented with a new fully dimensioned 2D drawing set.', ARRAY['Industrial', 'Steel', 'Drawings'], false, true, 77),
  ('gold-recovery-machine-part', 'Gold Recovery Machine Part', 'mechanical', '/projects/goldpart.jpg', ARRAY['/projects/goldpart.jpg', '/projects/sheets/goldpart.jpg'], 'Injection-moulded nozzle component built for chemical and corrosion resistance, with a threaded interface sized for a precise fit in the assembly.', ARRAY['Injection Molding', 'Chemical Resistant', 'Industrial'], false, true, 78),
  ('decorative-swing', 'Decorative Swing', 'printing', '/projects/swing.jpg', ARRAY['/projects/swing.jpg', '/projects/sheets/swing.jpg'], 'A supplied STL rebuilt as a fully editable parametric CAD model of the swing, ready for further modification, visualisation and manufacturing.', ARRAY['Reverse Eng.', 'Parametric', 'Decorative'], false, true, 79)
ON CONFLICT (slug) DO NOTHING;
